version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/package
    steps:
      - checkout
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: ./vendor/bin/phpunit