version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/package
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit